# LethPoly Subdomain Troubleshooting Guide
# For haccare.app → lethpoly.haccare.app

echo "🔧 LethPoly Subdomain Troubleshooting"
echo "====================================="
echo ""

echo "📍 Your Configuration:"
echo "  Primary Domain: haccare.app"
echo "  Tenant Subdomain: lethpoly.haccare.app"
echo "  Expected Result: LethPoly tenant should load"
echo ""

echo "✅ Step 1: Verify DNS Resolution"
echo "  Run these commands to test DNS:"
echo "  • curl -I https://haccare.app"
echo "  • curl -I https://lethpoly.haccare.app"
echo ""

echo "✅ Step 2: Check Netlify Configuration"
echo "  In Netlify Dashboard:"
echo "  1. Domain Settings → Custom domains"
echo "     • Add: haccare.app"
echo "     • Add: *.haccare.app"
echo "  2. SSL/TLS → Verify both domains have SSL"
echo "  3. Build & Deploy → Environment variables:"
echo "     • NODE_ENV=production"
echo "     • VITE_PRODUCTION_DOMAIN=haccare.app"
echo "     • VITE_SUBDOMAIN_ROUTING_ENABLED=true"
echo ""

echo "✅ Step 3: Verify Database Setup"
echo "  Run in Supabase SQL Editor:"
echo "  SELECT name, subdomain, status FROM tenants WHERE subdomain = 'lethpoly';"
echo ""

echo "✅ Step 4: Test Subdomain Routing"
echo "  1. Open browser dev tools (F12)"
echo "  2. Go to https://lethpoly.haccare.app"
echo "  3. Check Console for messages like:"
echo "     '🏢 Tenant subdomain detected: lethpoly'"
echo "  4. Check Network tab for failed requests"
echo ""

echo "🐛 Common Issues & Fixes:"
echo ""
echo "  Issue: 'Page cannot be displayed'"
echo "  → Check DNS propagation (up to 48 hours)"
echo "  → Verify wildcard DNS record: *.haccare.app"
echo ""
echo "  Issue: Main domain works, subdomain doesn't"
echo "  → Add *.haccare.app to Netlify domains"
echo "  → Check netlify.toml redirects"
echo ""
echo "  Issue: SSL certificate errors"
echo "  → Ensure SSL enabled for *.haccare.app in Netlify"
echo "  → Check certificate covers wildcard domains"
echo ""
echo "  Issue: Tenant not found errors"
echo "  → Run lethpoly-tenant-setup.sql"
echo "  → Verify subdomain = 'lethpoly' in database"
echo ""

echo "🔍 Debug Commands:"
echo "  # Test main domain"
echo "  curl -v https://haccare.app"
echo ""
echo "  # Test subdomain"
echo "  curl -v https://lethpoly.haccare.app"
echo ""
echo "  # Check DNS"
echo "  nslookup lethpoly.haccare.app"
echo ""
echo "  # Test local build"
echo "  npm run build && npm run preview"
echo ""

echo "📋 Deployment Checklist:"
echo "  □ netlify.toml updated with haccare.app"
echo "  □ Environment variables set in Netlify"
echo "  □ DNS wildcard record: *.haccare.app"
echo "  □ Custom domain added: haccare.app"
echo "  □ Wildcard domain added: *.haccare.app"
echo "  □ SSL enabled for both domains"
echo "  □ production-subdomain-setup.sql executed"
echo "  □ lethpoly-tenant-setup.sql executed"
echo "  □ Build successful and deployed"
echo ""

echo "🚀 Quick Test:"
echo "  1. https://haccare.app - Should load main app"
echo "  2. https://lethpoly.haccare.app - Should show LethPoly tenant"
echo "  3. Browser console should show: '🏢 Tenant subdomain detected: lethpoly'"
