import {
  Activity,
  Brain,
  BrainCircuit,
  Baby,
  Zap,
  Wind,
  Heart,
  Utensils,
  Droplet,
  Dumbbell,
  Layers,
  AlertTriangle,
  Shield,
  Lock,
  MapPin,
  Droplets,
  TestTube2,
  List,
  HeartHandshake,
  TrendingDown,
  Music,
  Accessibility,
  Calendar,
  Target,
  Users,
  Sparkles,
  MessageSquare,
  FileCheck,
  Stethoscope,
  ClipboardList,
  PenLine,
  Pill,
  Focus,
} from 'lucide-react';
import type { FlowsheetCategory, FlowsheetCategoryMeta, FlowsheetDefinition } from './types';

/** Ordered list of categories as they appear in the hub */
export const CATEGORY_ORDER: FlowsheetCategory[] = [
  'monitoring',
  'systems',
  'risk-safety',
  'wound-device',
  'fluid-metabolic',
  'mental-health',
  'therapeutic-rec',
  'clinical-docs',
];

export const CATEGORY_META: Record<FlowsheetCategory, FlowsheetCategoryMeta> = {
  monitoring: {
    id: 'monitoring',
    label: 'Monitoring & Vitals',
    description: 'Continuous monitoring, vital signs, and baseline assessments',
    icon: Activity,
    textColor: 'text-blue-700',
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
    borderAccent: 'border-t-blue-500',
    hoverRing: 'hover:ring-blue-200',
    badgeBg: 'bg-blue-100 text-blue-700',
  },
  systems: {
    id: 'systems',
    label: 'Systems Assessment',
    description: 'Head-to-toe body systems clinical assessment documentation',
    icon: Stethoscope,
    textColor: 'text-teal-700',
    iconBg: 'bg-teal-50',
    iconColor: 'text-teal-600',
    borderAccent: 'border-t-teal-500',
    hoverRing: 'hover:ring-teal-200',
    badgeBg: 'bg-teal-100 text-teal-700',
  },
  'risk-safety': {
    id: 'risk-safety',
    label: 'Risk & Safety',
    description: 'Clinical risk screening tools and patient safety assessments',
    icon: AlertTriangle,
    textColor: 'text-amber-700',
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-600',
    borderAccent: 'border-t-amber-500',
    hoverRing: 'hover:ring-amber-200',
    badgeBg: 'bg-amber-100 text-amber-700',
  },
  'wound-device': {
    id: 'wound-device',
    label: 'Wound & Device Care',
    description: 'Visual wound documentation and medical device management',
    icon: MapPin,
    textColor: 'text-rose-700',
    iconBg: 'bg-rose-50',
    iconColor: 'text-rose-600',
    borderAccent: 'border-t-rose-500',
    hoverRing: 'hover:ring-rose-200',
    badgeBg: 'bg-rose-100 text-rose-700',
  },
  'fluid-metabolic': {
    id: 'fluid-metabolic',
    label: 'Fluid & Metabolic',
    description: 'Fluid balance tracking, metabolic monitoring, and bowel documentation',
    icon: Droplets,
    textColor: 'text-cyan-700',
    iconBg: 'bg-cyan-50',
    iconColor: 'text-cyan-600',
    borderAccent: 'border-t-cyan-500',
    hoverRing: 'hover:ring-cyan-200',
    badgeBg: 'bg-cyan-100 text-cyan-700',
  },
  'mental-health': {
    id: 'mental-health',
    label: 'Mental Health & Cognition',
    description: 'Cognitive screening, mood assessment, and psychosocial documentation',
    icon: Brain,
    textColor: 'text-violet-700',
    iconBg: 'bg-violet-50',
    iconColor: 'text-violet-600',
    borderAccent: 'border-t-violet-500',
    hoverRing: 'hover:ring-violet-200',
    badgeBg: 'bg-violet-100 text-violet-700',
  },
  'therapeutic-rec': {
    id: 'therapeutic-rec',
    label: 'Therapeutic Recreation',
    description: 'TRG assessments for leisure, function, and quality of life in older adults',
    icon: Sparkles,
    textColor: 'text-emerald-700',
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
    borderAccent: 'border-t-emerald-500',
    hoverRing: 'hover:ring-emerald-200',
    badgeBg: 'bg-emerald-100 text-emerald-700',
  },
  'clinical-docs': {
    id: 'clinical-docs',
    label: 'Clinical Documentation',
    description: 'Care handover, directives, consents, and administrative forms',
    icon: ClipboardList,
    textColor: 'text-slate-700',
    iconBg: 'bg-slate-50',
    iconColor: 'text-slate-600',
    borderAccent: 'border-t-slate-500',
    hoverRing: 'hover:ring-slate-200',
    badgeBg: 'bg-slate-100 text-slate-700',
  },
};

export const FLOWSHEET_REGISTRY: FlowsheetDefinition[] = [
  // ── Monitoring & Vitals ────────────────────────────────────────────────────
  {
    id: 'vital-signs',
    title: 'Vital Signs',
    description: 'Temperature, blood pressure, heart rate, respiratory rate, and O₂ saturation',
    category: 'monitoring',
    icon: Activity,
    linkType: 'module-shortcut',
    moduleTarget: 'vitals',
  },
  {
    id: 'neurological',
    title: 'Neurological Assessment',
    description: 'GCS, pupil response, motor function, and level of consciousness',
    category: 'monitoring',
    icon: Brain,
    linkType: 'module-shortcut',
    moduleTarget: 'vitals',
  },
  {
    id: 'newborn',
    title: 'Newborn Assessment',
    description: 'APGAR scoring, newborn reflexes, and birth event documentation',
    category: 'monitoring',
    icon: Baby,
    linkType: 'module-shortcut',
    moduleTarget: 'vitals',
  },
  {
    id: 'pain',
    title: 'Pain Assessment',
    description: 'Pain scale, location, quality, aggravating factors, and response to intervention',
    category: 'monitoring',
    icon: Zap,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'pain',
  },

  // ── Systems Assessment ──────────────────────────────────────────────────────
  {
    id: 'respiratory',
    title: 'Respiratory',
    description: 'Breath sounds, work of breathing, oxygen therapy, and airway assessment',
    category: 'systems',
    icon: Wind,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'respiratory',
  },
  {
    id: 'cardiovascular',
    title: 'Cardiovascular',
    description: 'Heart sounds, peripheral pulses, capillary refill, edema, and rhythm',
    category: 'systems',
    icon: Heart,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'cardiovascular',
  },
  {
    id: 'gastrointestinal',
    title: 'Gastrointestinal',
    description: 'Bowel sounds, abdominal assessment, nausea, vomiting, and nutrition',
    category: 'systems',
    icon: Utensils,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'gastrointestinal',
  },
  {
    id: 'genitourinary',
    title: 'Genitourinary',
    description: 'Urine output, characteristics, catheter care, and GU system assessment',
    category: 'systems',
    icon: Droplet,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'genitourinary',
  },
  {
    id: 'musculoskeletal',
    title: 'Musculoskeletal',
    description: 'Range of motion, muscle strength, mobility level, and functional status',
    category: 'systems',
    icon: Dumbbell,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'musculoskeletal',
  },
  {
    id: 'integumentary',
    title: 'Integumentary',
    description: 'Skin colour, temperature, turgor, moisture, and integrity across body regions',
    category: 'systems',
    icon: Layers,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'integumentary',
  },

  // ── Risk & Safety ──────────────────────────────────────────────────────────
  {
    id: 'fall-risk',
    title: 'Fall Risk Assessment',
    description: 'Morse Fall Scale — identifies fall risk factors and prevention interventions',
    category: 'risk-safety',
    icon: AlertTriangle,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'fall-risk',
  },
  {
    id: 'braden-scale',
    title: 'Pressure Injury Risk',
    description: 'Braden Scale — sensory perception, moisture, activity, mobility, nutrition, friction',
    category: 'risk-safety',
    icon: Shield,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'braden-scale',
  },
  {
    id: 'restraint',
    title: 'Restraint Assessment',
    description: 'Restraint order documentation, clinical rationale, and least-restraint alternatives',
    category: 'risk-safety',
    icon: Lock,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'restraint',
  },

  // ── Wound & Device Care ────────────────────────────────────────────────────
  {
    id: 'device-placement',
    title: 'Device Placement',
    description: 'Visual placement of IVs, catheters, NG tubes, and medical devices on body diagram',
    category: 'wound-device',
    icon: MapPin,
    linkType: 'module-shortcut',
    moduleTarget: 'hacmap',
  },
  {
    id: 'wound-assessment',
    title: 'Wound Assessment',
    description: 'Wound location, dimensions, exudate, staging, and dressing documentation',
    category: 'wound-device',
    icon: Focus,
    linkType: 'module-shortcut',
    moduleTarget: 'hacmap',
  },

  // ── Fluid & Metabolic ─────────────────────────────────────────────────────
  {
    id: 'intake-output',
    title: 'Intake & Output',
    description: 'Fluid balance tracking — all intake sources and output measurements',
    category: 'fluid-metabolic',
    icon: Droplets,
    linkType: 'module-shortcut',
    moduleTarget: 'intake-output',
  },
  {
    id: 'blood-glucose',
    title: 'Blood Glucose (BBIT)',
    description: 'Bedside blood glucose monitoring and insulin administration record',
    category: 'fluid-metabolic',
    icon: TestTube2,
    linkType: 'module-shortcut',
    moduleTarget: 'medications',
  },
  {
    id: 'bowel',
    title: 'Bowel Assessment',
    description: 'Stool characteristics, frequency, continence, and bowel management plan',
    category: 'fluid-metabolic',
    icon: List,
    linkType: 'module-shortcut',
    moduleTarget: 'forms',
  },

  // ── Mental Health & Cognition ──────────────────────────────────────────────
  {
    id: 'biopsychosocial',
    title: 'Biopsychosocial',
    description: 'Holistic assessment of biological, psychological, and social health determinants',
    category: 'mental-health',
    icon: HeartHandshake,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'biopsychosocial',
  },
  {
    id: 'cognitive-screening',
    title: 'Cognitive Screening',
    description: 'Orientation, memory, executive function, and delirium screening tools',
    category: 'mental-health',
    icon: BrainCircuit,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'cognitive',
  },
  {
    id: 'mood-assessment',
    title: 'Mood & Affect',
    description: 'Mood screening, affect documentation, and emotional wellbeing assessment',
    category: 'mental-health',
    icon: TrendingDown,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'mood',
  },

  // ── Therapeutic Recreation ─────────────────────────────────────────────────
  {
    id: 'tr-leisure-interest',
    title: 'Leisure Interest Inventory',
    description: 'Client leisure history, interests, and past participation in meaningful activities',
    category: 'therapeutic-rec',
    icon: Music,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-leisure-interest',
    programs: ['TRG'],
  },
  {
    id: 'tr-functional',
    title: 'Functional Assessment',
    description: 'ADL capacity, physical function, and barriers to recreational participation',
    category: 'therapeutic-rec',
    icon: Accessibility,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-functional',
    programs: ['TRG'],
  },
  {
    id: 'tr-social',
    title: 'Social Participation',
    description: 'Social engagement levels, isolation risk, and community connection assessment',
    category: 'therapeutic-rec',
    icon: Users,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-social',
    programs: ['TRG'],
  },
  {
    id: 'tr-goals',
    title: 'TR Goal Setting',
    description: 'Therapeutic recreation goals, intervention plans, and measurable outcomes',
    category: 'therapeutic-rec',
    icon: Target,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-goals',
    programs: ['TRG'],
  },
  {
    id: 'tr-participation',
    title: 'Activity Participation',
    description: 'Documentation of activity sessions, client engagement, and observed responses',
    category: 'therapeutic-rec',
    icon: Calendar,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-participation',
    programs: ['TRG'],
  },
  {
    id: 'tr-qol',
    title: 'Quality of Life',
    description: 'QoL screening — wellbeing across physical, social, and emotional domains',
    category: 'therapeutic-rec',
    icon: Sparkles,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'tr-qol',
    programs: ['TRG'],
  },

  // ── Clinical Documentation ─────────────────────────────────────────────────
  {
    id: 'handover-notes',
    title: 'Handover Notes (SBAR)',
    description: 'Situation, Background, Assessment, Recommendation care transition communication',
    category: 'clinical-docs',
    icon: MessageSquare,
    linkType: 'module-shortcut',
    moduleTarget: 'handover',
  },
  {
    id: 'advanced-directives',
    title: 'Advanced Directives',
    description: 'DNR status, living will, substitute decision-maker, and organ donation preferences',
    category: 'clinical-docs',
    icon: FileCheck,
    linkType: 'module-shortcut',
    moduleTarget: 'advanced-directives',
  },
  {
    id: 'nursing-assessment',
    title: 'Nursing Assessment',
    description: 'Comprehensive head-to-toe nursing assessment with clinical judgment documentation',
    category: 'clinical-docs',
    icon: Stethoscope,
    linkType: 'module-shortcut',
    moduleTarget: 'forms',
  },
  {
    id: 'admission-assessment',
    title: 'Admission Assessment',
    description: 'Admission screening, chief complaint, medical history, and initial care plan',
    category: 'clinical-docs',
    icon: ClipboardList,
    linkType: 'module-shortcut',
    moduleTarget: 'forms',
  },
  {
    id: 'consents',
    title: 'Consents',
    description: 'Informed consent documentation for procedures, surgery, and treatment plans',
    category: 'clinical-docs',
    icon: PenLine,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'consent',
  },
  {
    id: 'bpmh',
    title: 'BPMH',
    description: 'Best Possible Medication History for medication reconciliation on admission',
    category: 'clinical-docs',
    icon: Pill,
    linkType: 'native',
    status: 'coming-soon',
    systemType: 'bpmh',
  },
];
