/**
 * Auto-Generated Simulation Student Service
 *
 * Creates disposable "simulation-only" student logins for the "auto-generate
 * student" option on Launch Simulation, and tracks them against the launched
 * simulation so credentials can be looked up again later. Account creation
 * goes through the create-simulation-student edge function (Admin API,
 * service role) instead of client-side signUp() — signUp() always triggers
 * Supabase's built-in confirmation email, which bounced in SMTP2GO since
 * these accounts use fake, non-deliverable addresses.
 */

import { supabase } from '../../lib/api/supabase';
import { addStudentToRoster } from '../admin/programService';
import { secureLogger } from '../../lib/security/secureLogger';

export interface AutoGeneratedStudentCredential {
  userId: string;
  email: string;
  password: string;
  studentNumber: string;
  label: string;
}

export interface SimulationAutoStudent {
  id: string;
  simulation_id: string;
  user_id: string;
  program_id: string | null;
  student_number: string;
  email: string;
  temp_password: string;
  label: string | null;
  created_at: string;
}

// Avoid visually ambiguous characters (0/O, 1/l/I) since these get read aloud/typed
const READABLE_LETTERS = 'abcdefghjkmnpqrstuvwxyz';
const READABLE_DIGITS = '23456789';

function randomFrom(chars: string, length: number): string {
  // crypto.getRandomValues, not Math.random() — this backs actual login passwords.
  const bytes = new Uint32Array(length);
  crypto.getRandomValues(bytes);
  let out = '';
  for (let i = 0; i < length; i++) {
    out += chars[bytes[i] % chars.length];
  }
  return out;
}

/** Short, easy-to-read password, e.g. "Mud72567" (1 upper + 2 lower + 5 digits). */
function generatePassword(): string {
  return `${randomFrom(READABLE_LETTERS, 1).toUpperCase()}${randomFrom(READABLE_LETTERS, 2)}${randomFrom(READABLE_DIGITS, 5)}`;
}

/** Short numeric code shared by the email and student number, e.g. "247". */
function generateLoginCode(): string {
  return randomFrom(READABLE_DIGITS, 3);
}

function generateStudentNumber(code: string): string {
  return `SIM${code}`;
}

function generateEmail(code: string): string {
  // Real domain we own, but a local-part no real person would sign up with —
  // never needs to receive mail. Created via the create-simulation-student
  // edge function (Admin API), which never sends a confirmation email.
  return `sim${code}@haccare.app`;
}

/**
 * Creates one disposable simulation-only student login: auth user + profile
 * (role='student', simulation_only=true) + program roster entry.
 */
export async function createAutoGeneratedStudent(
  programId: string,
  label: string
): Promise<AutoGeneratedStudentCredential> {
  const password = generatePassword();
  const maxAttempts = 5;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const code = generateLoginCode();
    const email = generateEmail(code);
    const studentNumber = generateStudentNumber(code);

    // Created via the Admin API (service role, in the edge function) rather
    // than client-side signUp() — signUp() always fires Supabase's built-in
    // confirmation email, which bounces for these fake addresses. The Admin
    // API creates the account pre-confirmed and never sends any email.
    const { data: fnData, error: fnError } = await supabase.functions.invoke('create-simulation-student', {
      body: { email, password, firstName: 'Sim', lastName: label }
    });

    if (fnError) {
      if (attempt < maxAttempts) continue;
      throw new Error(fnError.message || 'Could not generate a unique simulation student login — please try again');
    }
    // Code already taken (email collision) — short code space, so retry with a new one.
    if (!fnData?.success || !fnData?.userId) {
      if (fnData?.code === 'email_exists' && attempt < maxAttempts) continue;
      throw new Error(fnData?.error || 'Could not generate a unique simulation student login — please try again');
    }

    const userId = fnData.userId as string;

    // Wait for the DB trigger to create the user_profiles row before updating it
    await new Promise(resolve => setTimeout(resolve, 800));

    const { error: profileError } = await supabase.rpc('update_user_profile_admin', {
      p_user_id: userId,
      p_first_name: 'Sim',
      p_last_name: label,
      p_role: 'student',
      p_department: null,
      p_license_number: null,
      p_phone: null,
      p_is_active: true,
      p_simulation_only: true
    });

    if (profileError) throw profileError;

    const { error: rosterError } = await addStudentToRoster(programId, userId, studentNumber);
    if (rosterError) throw rosterError;

    return { userId, email, password, studentNumber, label };
  }

  throw new Error('Could not generate a unique simulation student login — please try again');
}

/** Persists generated credentials against the launched simulation for later lookup. */
export async function recordSimulationAutoStudents(
  simulationId: string,
  programId: string,
  credentials: AutoGeneratedStudentCredential[]
): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const rows = credentials.map(c => ({
    simulation_id: simulationId,
    user_id: c.userId,
    program_id: programId,
    student_number: c.studentNumber,
    email: c.email,
    temp_password: c.password,
    label: c.label,
    created_by: user.id
  }));

  const { error } = await supabase.from('simulation_auto_students').insert(rows);
  if (error) {
    secureLogger.error('Error recording simulation auto students:', error);
    throw error;
  }
}

/** Fetches previously generated logins for a simulation (for later lookup). */
export async function getSimulationAutoStudents(simulationId: string): Promise<SimulationAutoStudent[]> {
  const { data, error } = await supabase
    .from('simulation_auto_students')
    .select('*')
    .eq('simulation_id', simulationId)
    .order('created_at', { ascending: true });

  if (error) {
    secureLogger.error('Error fetching simulation auto students:', error);
    throw error;
  }
  return (data || []) as SimulationAutoStudent[];
}

export interface SimulationAutoStudentWithSimulation extends SimulationAutoStudent {
  simulation: { name: string; status: string } | null;
}

/** Fetches every auto-generated login created for a program, with the simulation it's tied to. */
export async function getSimulationAutoStudentsByProgram(
  programId: string
): Promise<SimulationAutoStudentWithSimulation[]> {
  const { data, error } = await supabase
    .from('simulation_auto_students')
    .select('*, simulation:simulation_active(name, status)')
    .eq('program_id', programId)
    .order('created_at', { ascending: false });

  if (error) {
    secureLogger.error('Error fetching program simulation auto students:', error);
    throw error;
  }
  return (data || []) as unknown as SimulationAutoStudentWithSimulation[];
}

