/**
 * Auto-Generated Simulation Student Service
 *
 * Creates disposable "simulation-only" student logins for the "auto-generate
 * student" option on Launch Simulation, and tracks them against the launched
 * simulation so credentials can be looked up again later. Account creation
 * mirrors the manual flow in AddStudentModal.tsx (client-side signUp — this
 * project has no admin/service-role edge function for user creation).
 */

import { supabase, createEphemeralAuthClient } from '../../lib/api/supabase';
import { addStudentToRoster } from '../admin/programService';
import { secureLogger } from '../../lib/security/secureLogger';

export interface AutoGeneratedStudentCredential {
  userId: string;
  email: string;
  password: string;
  studentNumber: string;
  label: string;
}

export interface SimulationAutoStudent {
  id: string;
  simulation_id: string;
  user_id: string;
  program_id: string | null;
  student_number: string;
  email: string;
  temp_password: string;
  label: string | null;
  created_at: string;
}

// Avoid visually ambiguous characters (0/O, 1/l/I) since these get read aloud/typed
const READABLE_LETTERS = 'abcdefghjkmnpqrstuvwxyz';
const READABLE_DIGITS = '23456789';

function randomFrom(chars: string, length: number): string {
  // crypto.getRandomValues, not Math.random() — this backs actual login passwords.
  const bytes = new Uint32Array(length);
  crypto.getRandomValues(bytes);
  let out = '';
  for (let i = 0; i < length; i++) {
    out += chars[bytes[i] % chars.length];
  }
  return out;
}

/** Short, easy-to-read password, e.g. "Mud72567" (1 upper + 2 lower + 5 digits). */
function generatePassword(): string {
  return `${randomFrom(READABLE_LETTERS, 1).toUpperCase()}${randomFrom(READABLE_LETTERS, 2)}${randomFrom(READABLE_DIGITS, 5)}`;
}

/** Short numeric code shared by the email and student number, e.g. "247". */
function generateLoginCode(): string {
  return randomFrom(READABLE_DIGITS, 3);
}

function generateStudentNumber(code: string): string {
  return `SIM${code}`;
}

function generateEmail(code: string): string {
  // Real domain we own, but a local-part no real person would sign up with —
  // never needs to receive mail, since confirm_simulation_student_email()
  // marks the account confirmed directly.
  return `sim${code}@haccare.app`;
}

/**
 * Creates one disposable simulation-only student login: auth user + profile
 * (role='student', simulation_only=true) + program roster entry.
 */
export async function createAutoGeneratedStudent(
  programId: string,
  label: string
): Promise<AutoGeneratedStudentCredential> {
  const password = generatePassword();
  const maxAttempts = 5;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const code = generateLoginCode();
    const email = generateEmail(code);
    const studentNumber = generateStudentNumber(code);

    // Use an isolated client for signUp — on the shared `supabase` client this
    // would silently swap the current session to the new student, breaking
    // every call after it (roster insert, launch_simulation) for the instructor.
    const { data: authData, error: authError } = await createEphemeralAuthClient().auth.signUp({
      email,
      password,
      options: {
        data: {
          first_name: 'Sim',
          last_name: label
        }
      }
    });

    // Code already taken (email collision) — short code space, so retry with a new one.
    if (authError || !authData.user || authData.user.identities?.length === 0) {
      if (attempt < maxAttempts) continue;
      throw authError || new Error('Could not generate a unique simulation student login — please try again');
    }

    // Wait for the DB trigger to create the user_profiles row before updating it
    await new Promise(resolve => setTimeout(resolve, 800));

    const { error: profileError } = await supabase.rpc('update_user_profile_admin', {
      p_user_id: authData.user.id,
      p_first_name: 'Sim',
      p_last_name: label,
      p_role: 'student',
      p_department: null,
      p_license_number: null,
      p_phone: null,
      p_is_active: true,
      p_simulation_only: true
    });

    if (profileError) throw profileError;

    // Fake email can never receive a real confirmation link — mark it confirmed
    // directly so the account can sign in immediately.
    const { error: confirmError } = await supabase.rpc('confirm_simulation_student_email', {
      p_user_id: authData.user.id
    });
    if (confirmError) throw confirmError;

    const { error: rosterError } = await addStudentToRoster(programId, authData.user.id, studentNumber);
    if (rosterError) throw rosterError;

    return { userId: authData.user.id, email, password, studentNumber, label };
  }

  throw new Error('Could not generate a unique simulation student login — please try again');
}

/** Persists generated credentials against the launched simulation for later lookup. */
export async function recordSimulationAutoStudents(
  simulationId: string,
  programId: string,
  credentials: AutoGeneratedStudentCredential[]
): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const rows = credentials.map(c => ({
    simulation_id: simulationId,
    user_id: c.userId,
    program_id: programId,
    student_number: c.studentNumber,
    email: c.email,
    temp_password: c.password,
    label: c.label,
    created_by: user.id
  }));

  const { error } = await supabase.from('simulation_auto_students').insert(rows);
  if (error) {
    secureLogger.error('Error recording simulation auto students:', error);
    throw error;
  }
}

/** Fetches previously generated logins for a simulation (for later lookup). */
export async function getSimulationAutoStudents(simulationId: string): Promise<SimulationAutoStudent[]> {
  const { data, error } = await supabase
    .from('simulation_auto_students')
    .select('*')
    .eq('simulation_id', simulationId)
    .order('created_at', { ascending: true });

  if (error) {
    secureLogger.error('Error fetching simulation auto students:', error);
    throw error;
  }
  return (data || []) as SimulationAutoStudent[];
}
