/**
 * ===========================================================================
 * LAUNCH SIMULATION MODAL
 * ===========================================================================
 * Select duration and participants when launching a simulation from template
 * ===========================================================================
 */

import React, { useState, useEffect } from 'react';
import { X, Play, Users, Clock, AlertCircle, Tag, KeyRound, Copy, Check, Plus, Trash2, DoorOpen, Layers } from 'lucide-react';
import { launchSimulation, getTemplateStates } from '../../../services/simulation/simulationService';
import { supabase } from '../../../lib/api/supabase';
import type { SimulationTemplateWithDetails } from '../types/simulation';
import { SUB_CATEGORIES } from '../types/simulation';
import { secureLogger } from '../../../lib/security/secureLogger';
import { useTenant } from '../../../contexts/TenantContext';
import { getPrograms, type Program } from '../../../services/admin/programService';
import {
  createAutoGeneratedStudent,
  recordSimulationAutoStudents,
  rollbackAutoGeneratedStudents,
  type AutoGeneratedStudentCredential,
} from '../../../services/simulation/autoStudentService';

interface LaunchSimulationModalProps {
  template: SimulationTemplateWithDetails;
  onClose: () => void;
  onSuccess: () => void;
}

interface UserOption {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  role: string;
}

interface RoomEntry {
  roomNumber: string;
  instructorId: string;
}

interface TemplateStateOption { id: string; label: string; }

const INSTRUCTOR_ELIGIBLE_ROLES = ['instructor', 'coordinator', 'admin', 'super_admin'];

const LaunchSimulationModal: React.FC<LaunchSimulationModalProps> = ({
  template,
  onClose,
  onSuccess,
}) => {
  const { currentTenant } = useTenant();
  const [formData, setFormData] = useState({
    name: '',  // Start with empty field so user can customize
    duration_minutes: template.default_duration_minutes,
    participant_user_ids: [] as string[],
    participant_roles: [] as ('instructor' | 'student')[],
    primary_categories: [] as string[],
    sub_categories: [] as string[],
  });
  const [users, setUsers] = useState<UserOption[]>([]);
  const [programs, setPrograms] = useState<Program[]>([]);
  const [templateStates, setTemplateStates] = useState<TemplateStateOption[]>([]);
  const [selectedStateId, setSelectedStateId] = useState<string>('');
  const [launchMode, setLaunchMode] = useState<'single' | 'rooms'>('single');
  const [rooms, setRooms] = useState<RoomEntry[]>([{ roomNumber: '', instructorId: '' }]);
  const [roomLaunchProgress, setRoomLaunchProgress] = useState<string | null>(null);
  const [autoGenerate, setAutoGenerate] = useState(false);
  const [autoGenerateCount, setAutoGenerateCount] = useState(1);
  const [generatedCredentials, setGeneratedCredentials] = useState<AutoGeneratedStudentCredential[] | null>(null);
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(false);
  const [loadingUsers, setLoadingUsers] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadPrograms = async () => {
    if (!currentTenant) return;

    // If in a program tenant, that's the only program available; otherwise
    // load all programs for the parent tenant (mirrors CreateTemplateModal).
    if (currentTenant.program_id) {
      const { data } = await supabase
        .from('programs')
        .select('*')
        .eq('id', currentTenant.program_id)
        .single();
      if (data) setPrograms([data]);
    } else {
      const { data, error } = await getPrograms(currentTenant.id);
      if (!error && data) setPrograms(data);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadPrograms();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTenant]);

  useEffect(() => {
    getTemplateStates(template.id).then(setTemplateStates).catch(() => setTemplateStates([]));
  }, [template.id]);

  const loadUsers = async () => {
    if (!currentTenant) return;

    try {
      // Scope to this institution: its own tenant plus every program tenant
      // underneath it (never pull users from other institutions).
      const institutionTenantId = currentTenant.tenant_type === 'program' && currentTenant.parent_tenant_id
        ? currentTenant.parent_tenant_id
        : currentTenant.id;

      const { data: programTenants } = await supabase
        .from('tenants')
        .select('id')
        .eq('parent_tenant_id', institutionTenantId);

      const tenantIds = [institutionTenantId, ...(programTenants || []).map(t => t.id)];

      const results = await Promise.all(
        tenantIds.map(id => supabase.rpc('get_tenant_users', { target_tenant_id: id }))
      );

      const byId = new Map<string, UserOption>();
      for (const { data, error } of results) {
        if (error || !data) continue;
        for (const row of data as Array<{ user_id: string; first_name: string; last_name: string; email: string; role: string; is_active: boolean }>) {
          if (row.is_active === false) continue;
          byId.set(row.user_id, {
            id: row.user_id,
            first_name: row.first_name,
            last_name: row.last_name,
            email: row.email,
            role: row.role,
          });
        }
      }

      setUsers([...byId.values()].sort((a, b) => (a.first_name || '').localeCompare(b.first_name || '')));
    } catch (err) {
      secureLogger.error('Error loading users:', err);
    } finally {
      setLoadingUsers(false);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadUsers();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTenant]);

  const handleUserToggle = (userId: string, role: 'instructor' | 'student') => {
    const index = formData.participant_user_ids.indexOf(userId);
    
    if (index >= 0) {
      // Remove user
      const newIds = [...formData.participant_user_ids];
      const newRoles = [...formData.participant_roles];
      newIds.splice(index, 1);
      newRoles.splice(index, 1);
      setFormData({
        ...formData,
        participant_user_ids: newIds,
        participant_roles: newRoles,
      });
    } else {
      // Add user
      setFormData({
        ...formData,
        participant_user_ids: [...formData.participant_user_ids, userId],
        participant_roles: [...formData.participant_roles, role],
      });
    }
  };

  const getUserRole = (userId: string): 'instructor' | 'student' | null => {
    const index = formData.participant_user_ids.indexOf(userId);
    return index >= 0 ? formData.participant_roles[index] : null;
  };

  const addRoom = () => setRooms([...rooms, { roomNumber: '', instructorId: '' }]);
  const removeRoom = (index: number) => setRooms(rooms.filter((_, i) => i !== index));
  const updateRoom = (index: number, patch: Partial<RoomEntry>) => {
    setRooms(rooms.map((room, i) => (i === index ? { ...room, ...patch } : room)));
  };

  const roomsAreValid = rooms.length > 0 && rooms.every(r => r.roomNumber.trim() && r.instructorId);

  const handleSubmitRooms = async () => {
    if (!roomsAreValid) {
      setError('Every room needs a room number and an assigned instructor');
      return;
    }
    if (autoGenerate && formData.primary_categories.length !== 1) {
      setError('Select exactly one Program category above to enroll the auto-generated student(s).');
      return;
    }

    setLoading(true);
    setError(null);

    // Hoisted above the try so the `finally` block below can tell whether any
    // room actually launched — if none did, these accounts never became real
    // simulation participants and must be rolled back instead of left orphaned.
    let generated: AutoGeneratedStudentCredential[] = [];
    let launchedCount = 0;

    try {
      // Shared student login(s) — generated once, added to every room.
      let autoGenerateProgram: Program | null = null;

      if (autoGenerate) {
        autoGenerateProgram = programs.find(p => p.code === formData.primary_categories[0]) || null;
        if (!autoGenerateProgram) {
          throw new Error('Could not find the selected program to enroll auto-generated students.');
        }
        for (let i = 0; i < autoGenerateCount; i++) {
          const label = autoGenerateCount > 1 ? `Auto Student ${i + 1}` : 'Auto Student';
          generated.push(await createAutoGeneratedStudent(autoGenerateProgram.id, label));
        }
      }

      const failures: string[] = [];

      for (let i = 0; i < rooms.length; i++) {
        const room = rooms[i];
        setRoomLaunchProgress(`Launching room ${i + 1} of ${rooms.length}...`);

        try {
          const result = await launchSimulation({
            template_id: template.id,
            name: `Room ${room.roomNumber.trim()} - ${template.name}`,
            duration_minutes: formData.duration_minutes,
            participant_user_ids: [room.instructorId, ...generated.map(g => g.userId)],
            participant_roles: ['instructor', ...generated.map(() => 'student' as const)],
            primary_categories: formData.primary_categories,
            sub_categories: formData.sub_categories,
            state_id: selectedStateId || null,
          });

          const launchResult = Array.isArray(result) ? result[0] : result;

          if (launchResult && launchResult.simulation_id) {
            launchedCount++;
            if (generated.length > 0 && autoGenerateProgram) {
              // Room already launched with these students as real participants —
              // a tracking failure here must NOT trigger account rollback below.
              try {
                await recordSimulationAutoStudents(launchResult.simulation_id, autoGenerateProgram.id, generated);
              } catch (recordErr: unknown) {
                const msg = recordErr instanceof Error ? recordErr.message : 'Unknown error';
                failures.push(`Room ${room.roomNumber}: launched, but saving the student login for later lookup failed (student can still log in) — ${msg}`);
              }
            }
          } else {
            failures.push(`Room ${room.roomNumber}: ${launchResult?.message || 'Failed to launch'}`);
          }
        } catch (roomErr: unknown) {
          const msg = roomErr instanceof Error ? roomErr.message : 'Unknown error';
          failures.push(`Room ${room.roomNumber}: ${msg}`);
        }
      }

      setRoomLaunchProgress(null);

      if (generated.length > 0) {
        setGeneratedCredentials(generated);
      }

      if (failures.length > 0) {
        setError(`${launchedCount} of ${rooms.length} room(s) launched. Failed:\n${failures.join('\n')}`);
        if (launchedCount === 0) return;
      }

      if (generated.length === 0) {
        alert(`${launchedCount} room(s) launched successfully!`);
        onSuccess();
      }
    } catch (err: unknown) {
      secureLogger.error('Error launching rooms:', err);
      setError(err instanceof Error ? err.message : 'An unexpected error occurred');
    } finally {
      if (launchedCount === 0 && generated.length > 0) {
        await rollbackAutoGeneratedStudents(generated);
      }
      setLoading(false);
      setRoomLaunchProgress(null);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (launchMode === 'rooms') {
      await handleSubmitRooms();
      return;
    }
    
    if (formData.participant_user_ids.length === 0) {
      setError('Please select at least one participant');
      return;
    }

    if (autoGenerate && formData.primary_categories.length !== 1) {
      setError('Select exactly one Program category above to enroll the auto-generated student(s).');
      return;
    }

    setLoading(true);
    setError(null);

    // Hoisted above the try so the `finally` block below can tell whether the
    // simulation actually launched — if not, these accounts never became real
    // simulation participants and must be rolled back instead of left orphaned.
    let generated: AutoGeneratedStudentCredential[] = [];
    let simulationLaunched = false;

    try {
      let autoGenerateProgram: Program | null = null;

      if (autoGenerate) {
        autoGenerateProgram = programs.find(p => p.code === formData.primary_categories[0]) || null;
        if (!autoGenerateProgram) {
          throw new Error('Could not find the selected program to enroll auto-generated students.');
        }

        for (let i = 0; i < autoGenerateCount; i++) {
          const label = autoGenerateCount > 1 ? `Auto Student ${i + 1}` : 'Auto Student';
          generated.push(await createAutoGeneratedStudent(autoGenerateProgram.id, label));
        }
      }

      const result = await launchSimulation({
        template_id: template.id,
        name: formData.name,
        duration_minutes: formData.duration_minutes,
        participant_user_ids: [...formData.participant_user_ids, ...generated.map(g => g.userId)],
        participant_roles: [...formData.participant_roles, ...generated.map(() => 'student' as const)],
        primary_categories: formData.primary_categories,
        sub_categories: formData.sub_categories,
        state_id: selectedStateId || null,
      });

      // RPC returns array with single row
      const launchResult = Array.isArray(result) ? result[0] : result;
      
      if (launchResult && launchResult.simulation_id) {
        simulationLaunched = true;
        if (generated.length > 0 && autoGenerateProgram) {
          // Simulation already launched with these students as real participants —
          // a tracking failure here must NOT trigger account rollback below.
          try {
            await recordSimulationAutoStudents(launchResult.simulation_id, autoGenerateProgram.id, generated);
            setGeneratedCredentials(generated);
          } catch (recordErr: unknown) {
            secureLogger.error('Error recording auto-generated student tracking:', recordErr);
            setGeneratedCredentials(generated);
            setError('Simulation launched and the student was added as a participant, but saving their login for later lookup failed — they can still log in, but note their credentials manually since this simulation won\'t auto-delete the account when removed.');
          }
        } else {
          alert(`Simulation launched successfully!\n\nSimulation ID: ${launchResult.simulation_id}\nTenant ID: ${launchResult.tenant_id}\n\nParticipants can now log in and access this simulation.`);
          onSuccess();
        }
      } else {
        setError(launchResult?.message || 'Failed to launch simulation');
      }
    } catch (err: unknown) {
      secureLogger.error('Error launching simulation:', err);
      const errMsg = err instanceof Error ? err.message : '';
      // Provide user-friendly error messages
      if (errMsg.includes('Template not found or not ready')) {
        setError('This template is not ready to launch. Please save a snapshot first by:\n1. Building your scenario (add patients, medications, etc.)\n2. Click the "Save Snapshot" button on the template\n3. Then try launching again');
      } else if (errMsg.includes('Template has no snapshot data')) {
        setError('This template has no saved snapshot. Please save a snapshot before launching.');
      } else {
        setError(errMsg || 'An unexpected error occurred');
      }
    } finally {
      if (!simulationLaunched && generated.length > 0) {
        await rollbackAutoGeneratedStudents(generated);
      }
      setLoading(false);
    }
  };

  // Auto-generated students were created and the simulation launched — show
  // their logins once now, and let the user look them up again later via the
  // simulation card's "Logins" button.
  if (generatedCredentials) {
    const handleCopyAll = async () => {
      const text = generatedCredentials
        .map(c => `${c.label}\nEmail: ${c.email}\nPassword: ${c.password}\nStudent #: ${c.studentNumber}`)
        .join('\n\n');
      try {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch {
        // Clipboard API may be unavailable (e.g. insecure context) — credentials are still visible on screen.
      }
    };

    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
          <div className="flex items-center gap-3 p-6 border-b border-slate-200 dark:border-slate-700">
            <div className="p-2 bg-gradient-to-br from-green-500 to-emerald-600 rounded-lg">
              <KeyRound className="h-5 w-5 text-white" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">Simulation Launched</h2>
          </div>

          <div className="p-6 space-y-4">
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Hand these logins to the student(s) at the workstation. You can view them again later from this simulation's "Logins" button.
            </p>

            {generatedCredentials.map((c) => (
              <div key={c.userId} className="border border-slate-200 dark:border-slate-700 rounded-lg p-3 space-y-1">
                <p className="text-sm font-medium text-slate-900 dark:text-white">{c.label}</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">Student #: {c.studentNumber}</p>
                <p className="text-sm font-mono text-slate-800 dark:text-slate-200">{c.email}</p>
                <p className="text-sm font-mono text-slate-800 dark:text-slate-200">{c.password}</p>
              </div>
            ))}

            <button
              type="button"
              onClick={handleCopyAll}
              className="w-full flex items-center justify-center gap-2 px-4 py-2 border border-slate-300 dark:border-slate-600 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
            >
              {copied ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
              {copied ? 'Copied!' : 'Copy All'}
            </button>

            <button
              type="button"
              onClick={onSuccess}
              className="w-full px-4 py-2 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg hover:from-green-700 hover:to-emerald-700 transition-all shadow-md"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-200 dark:border-slate-700">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-br from-green-500 to-emerald-600 rounded-lg">
              <Play className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                Launch Simulation
              </h2>
              <p className="text-sm text-slate-600 dark:text-slate-400">
                From template: {template.name}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
          >
            <X className="h-5 w-5 text-slate-500" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6 space-y-4">
          {/* Warning if no snapshot */}
          {!template.snapshot_data && (
            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
              <div className="flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
                <div className="text-sm text-yellow-900 dark:text-yellow-100">
                  <strong>Template Not Ready!</strong>
                  <p className="mt-1">This template has no saved snapshot. You must:</p>
                  <ol className="list-decimal list-inside mt-1 space-y-1 ml-2">
                    <li>Build your scenario (add patients, medications, etc.)</li>
                    <li>Click "Save Snapshot" button on the template</li>
                    <li>Then return here to launch</li>
                  </ol>
                </div>
              </div>
            </div>
          )}

          {/* Info Banner */}
          {template.snapshot_data && (
            <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg p-3">
              <div className="flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-green-600 dark:text-green-400 flex-shrink-0 mt-0.5" />
                <div className="text-sm text-green-900 dark:text-green-100">
                  <strong>Launching will:</strong>
                  <ul className="list-disc list-inside mt-1 space-y-1">
                    <li>Create a new simulation tenant with template snapshot data</li>
                    <li>Grant selected participants access to the simulation</li>
                    <li>Start the simulation timer based on duration selected</li>
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* Launch Mode Toggle */}
          <div className="flex gap-2 p-1 bg-slate-100 dark:bg-slate-900/40 rounded-lg">
            <button
              type="button"
              onClick={() => setLaunchMode('single')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-md text-sm font-medium transition-all ${
                launchMode === 'single'
                  ? 'bg-white dark:bg-slate-700 shadow-sm text-slate-900 dark:text-white'
                  : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
              }`}
            >
              <Play className="h-4 w-4" />
              Single Simulation
            </button>
            <button
              type="button"
              onClick={() => setLaunchMode('rooms')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-md text-sm font-medium transition-all ${
                launchMode === 'rooms'
                  ? 'bg-white dark:bg-slate-700 shadow-sm text-slate-900 dark:text-white'
                  : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
              }`}
            >
              <DoorOpen className="h-4 w-4" />
              Multiple Rooms
            </button>
          </div>

          {launchMode === 'single' ? (
          <>
          {/* Simulation Name */}
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Simulation Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              id="name"
              required
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder={`e.g., Room 201 - ${template.name}, Class A Morning Session, ${new Date().toLocaleDateString()}`}
              className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-green-500 dark:bg-slate-700 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-500"
            />
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Give this simulation a unique name (e.g., room number, class section, or date)
            </p>
          </div>
          </>
          ) : (
          <>
          {/* Rooms */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              <DoorOpen className="inline h-4 w-4 mr-1" />
              Rooms &amp; Instructors <span className="text-red-500">*</span>
            </label>
            <div className="space-y-2">
              {rooms.map((room, index) => (
                <div key={index} className="flex items-center gap-2">
                  <input
                    type="text"
                    required
                    value={room.roomNumber}
                    onChange={(e) => updateRoom(index, { roomNumber: e.target.value })}
                    placeholder="Room #"
                    className="w-28 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-green-500 dark:bg-slate-700 dark:text-white placeholder:text-slate-400"
                  />
                  <select
                    required
                    value={room.instructorId}
                    onChange={(e) => updateRoom(index, { instructorId: e.target.value })}
                    className="flex-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-green-500 dark:bg-slate-700 dark:text-white"
                  >
                    <option value="">Select instructor...</option>
                    {users
                      .filter(u => INSTRUCTOR_ELIGIBLE_ROLES.includes(u.role))
                      .map(u => (
                        <option key={u.id} value={u.id}>{u.first_name} {u.last_name} ({u.role})</option>
                      ))}
                  </select>
                  <button
                    type="button"
                    onClick={() => removeRoom(index)}
                    disabled={rooms.length === 1}
                    className="p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
                    title="Remove room"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              ))}
            </div>
            <button
              type="button"
              onClick={addRoom}
              className="mt-2 flex items-center gap-1.5 text-sm font-medium text-green-600 hover:text-green-700"
            >
              <Plus className="h-4 w-4" />
              Add Room
            </button>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
              Launches one simulation per room, named "Room {'{'}number{'}'} - {template.name}". Each gets its own assigned instructor; any auto-generated student login below is shared across all rooms.
            </p>
          </div>
          </>
          )}

          {/* Launch From (default snapshot vs a saved named state) */}
          {templateStates.length > 0 && (
            <div>
              <label htmlFor="launch-state" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                <Layers className="inline h-4 w-4 mr-1" />
                Launch From
              </label>
              <select
                id="launch-state"
                value={selectedStateId}
                onChange={(e) => setSelectedStateId(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-green-500 dark:bg-slate-700 dark:text-white"
              >
                <option value="">Default (current template snapshot)</option>
                {templateStates.map((state) => (
                  <option key={state.id} value={state.id}>{state.label}</option>
                ))}
              </select>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                Pick a saved state (e.g. "Week 2") to launch the simulation with that data instead of the template's default.
              </p>
            </div>
          )}

          {/* Duration */}
          <div>
            <label htmlFor="duration" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              <Clock className="inline h-4 w-4 mr-1" />
              Duration (minutes) <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              id="duration"
              min="15"
              max="480"
              step="15"
              required
              value={formData.duration_minutes}
              onChange={(e) => setFormData({ ...formData, duration_minutes: parseInt(e.target.value) })}
              className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-green-500 dark:bg-slate-700 dark:text-white"
            />
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Simulation will auto-complete after this time expires
            </p>
          </div>

          {/* Primary Categories */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              <Tag className="inline h-4 w-4 mr-1" />
              Primary Category (Program)
            </label>
            {programs.length === 0 ? (
              <p className="text-xs text-slate-500 dark:text-slate-400">No programs found for this institution.</p>
            ) : (
              <div className="grid grid-cols-2 gap-3">
                {programs.map((program) => {
                  const isSelected = formData.primary_categories.includes(program.code);
                  return (
                    <label
                      key={program.id}
                      className={`
                        flex items-center gap-2 p-3 rounded-lg border-2 cursor-pointer transition-all
                        ${isSelected 
                          ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20' 
                          : 'border-slate-300 dark:border-slate-600 hover:border-slate-400 dark:hover:border-slate-500'
                        }
                      `}
                    >
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setFormData({
                              ...formData,
                              primary_categories: [...formData.primary_categories, program.code]
                            });
                          } else {
                            setFormData({
                              ...formData,
                              primary_categories: formData.primary_categories.filter(c => c !== program.code)
                            });
                          }
                        }}
                        className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <span className="px-2 py-1 rounded text-xs font-medium bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300">
                        {program.code}
                      </span>
                    </label>
                  );
                })}
              </div>
            )}
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Select one or more programs (optional)
            </p>
          </div>

          {/* Auto-Generate Simulation-Only Students */}
          <div className="border border-slate-300 dark:border-slate-600 rounded-lg p-4 bg-slate-50 dark:bg-slate-900/40">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={autoGenerate}
                onChange={(e) => setAutoGenerate(e.target.checked)}
                className="w-4 h-4 text-green-600 rounded focus:ring-green-500"
              />
              <KeyRound className="h-4 w-4 text-slate-500" />
              <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                Auto-generate simulation-only student login(s)
              </span>
            </label>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 ml-6">
              Creates a disposable student account (visible under that program's Active Simulation Student Logins page) so you can hand out a login at a shared workstation.
              It's automatically deleted only when this simulation is deleted — pause/reset/complete won't touch it.
            </p>
            {autoGenerate && (
              <div className="mt-3 ml-6 flex items-center gap-3 flex-wrap">
                <label className="text-sm text-slate-700 dark:text-slate-300">
                  Number of students:
                </label>
                <input
                  type="number"
                  min={1}
                  max={10}
                  value={autoGenerateCount}
                  onChange={(e) => setAutoGenerateCount(Math.max(1, Math.min(10, parseInt(e.target.value) || 1)))}
                  className="w-20 px-2 py-1 border border-slate-300 dark:border-slate-600 rounded-lg dark:bg-slate-700 dark:text-white"
                />
                {formData.primary_categories.length !== 1 && (
                  <span className="text-xs text-amber-600 dark:text-amber-400">
                    Select exactly one Program category above to enroll them.
                  </span>
                )}
              </div>
            )}
          </div>

          {/* Sub Categories */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              <Tag className="inline h-4 w-4 mr-1" />
              Sub-Category (Type)
            </label>
            <div className="grid grid-cols-3 gap-3">
              {SUB_CATEGORIES.map((category) => {
                const isSelected = formData.sub_categories.includes(category.value);
                return (
                  <label
                    key={category.value}
                    className={`
                      flex items-center gap-2 p-3 rounded-lg border-2 cursor-pointer transition-all
                      ${isSelected 
                        ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20' 
                        : 'border-slate-300 dark:border-slate-600 hover:border-slate-400 dark:hover:border-slate-500'
                      }
                    `}
                  >
                    <input
                      type="checkbox"
                      checked={isSelected}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setFormData({
                            ...formData,
                            sub_categories: [...formData.sub_categories, category.value]
                          });
                        } else {
                          setFormData({
                            ...formData,
                            sub_categories: formData.sub_categories.filter(c => c !== category.value)
                          });
                        }
                      }}
                      className="w-4 h-4 text-purple-600 rounded focus:ring-purple-500"
                    />
                    <span className={`px-2 py-1 rounded text-xs font-medium ${category.color}`}>
                      {category.label}
                    </span>
                  </label>
                );
              })}
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Select one or more types (optional)
            </p>
          </div>

          {/* Participants */}
          {launchMode === 'single' && (
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              <Users className="inline h-4 w-4 mr-1" />
              Select Participants <span className="text-red-500">*</span>
            </label>
            
            {loadingUsers ? (
              <div className="text-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-green-600 mx-auto"></div>
              </div>
            ) : (
              <div className="border border-slate-300 dark:border-slate-600 rounded-lg max-h-64 overflow-y-auto">
                {users.map((user) => {
                  const selectedRole = getUserRole(user.id);
                  
                  return (
                    <div
                      key={user.id}
                      className="flex items-center gap-3 p-3 border-b border-slate-200 dark:border-slate-700 last:border-b-0 hover:bg-slate-50 dark:hover:bg-slate-700/50"
                    >
                      <div className="flex-1">
                        <div className="font-medium text-slate-900 dark:text-white">
                          {user.first_name} {user.last_name}
                        </div>
                        <div className="text-sm text-slate-600 dark:text-slate-400">
                          {user.email} • {user.role}
                        </div>
                      </div>
                      
                      <div className="flex gap-2">
                        <button
                          type="button"
                          onClick={() => handleUserToggle(user.id, 'instructor')}
                          className={`
                            px-3 py-1 rounded text-sm font-medium transition-all
                            ${
                              selectedRole === 'instructor'
                                ? 'bg-purple-600 text-white'
                                : 'bg-slate-200 text-slate-700 hover:bg-purple-100 dark:bg-slate-600 dark:text-slate-300'
                            }
                          `}
                        >
                          Instructor
                        </button>
                        <button
                          type="button"
                          onClick={() => handleUserToggle(user.id, 'student')}
                          className={`
                            px-3 py-1 rounded text-sm font-medium transition-all
                            ${
                              selectedRole === 'student'
                                ? 'bg-blue-600 text-white'
                                : 'bg-slate-200 text-slate-700 hover:bg-blue-100 dark:bg-slate-600 dark:text-slate-300'
                            }
                          `}
                        >
                          Student
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
            
            {formData.participant_user_ids.length > 0 && (
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
                {formData.participant_user_ids.length} participant(s) selected
              </p>
            )}
          </div>
          )}

          {/* Error Message */}
          {error && (
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3">
              <p className="text-sm text-red-800 dark:text-red-200 whitespace-pre-line">{error}</p>
            </div>
          )}
        </form>

        {/* Actions */}
        <div className="flex gap-3 p-6 border-t border-slate-200 dark:border-slate-700">
          <button
            type="button"
            onClick={onClose}
            className="flex-1 px-4 py-2 border border-slate-300 dark:border-slate-600 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={
              loading ||
              (autoGenerate && formData.primary_categories.length !== 1) ||
              (launchMode === 'single' ? formData.participant_user_ids.length === 0 : !roomsAreValid)
            }
            className="flex-1 px-4 py-2 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg hover:from-green-700 hover:to-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md"
          >
            {loading
              ? (roomLaunchProgress || (autoGenerate ? 'Creating student login(s)...' : 'Launching...'))
              : launchMode === 'rooms'
                ? `Launch ${rooms.length} Room${rooms.length === 1 ? '' : 's'}`
                : 'Launch Simulation'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default LaunchSimulationModal;
