import React, { useState, useEffect } from 'react';
import { Shield, AlertCircle } from 'lucide-react';
import { supabase } from '../../lib/api/supabase';
import { secureLogger } from '../../lib/security/secureLogger';

interface MFAEnrollmentProps {
  onSuccess: () => void;
  onCancel: () => void;
}

export const MFAEnrollment: React.FC<MFAEnrollmentProps> = ({ onSuccess, onCancel }) => {
  const [qrCode, setQrCode] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [factorId, setFactorId] = useState<string | null>(null);
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [initialising, setInitialising] = useState(true);

  useEffect(() => {
    const startEnrollment = async () => {
      try {
        const { data, error: enrollError } = await supabase.auth.mfa.enroll({
          factorType: 'totp',
        });
        if (enrollError) throw enrollError;

        setFactorId(data.id);
        setQrCode(data.totp.qr_code);
        setSecret(data.totp.secret);
      } catch (err: any) {
        secureLogger.error('MFA enroll init failed:', err);
        setError(err.message ?? 'Failed to start MFA enrollment. Please try again.');
      } finally {
        setInitialising(false);
      }
    };

    startEnrollment();
  }, []);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!factorId) return;

    setError('');
    setLoading(true);

    const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({
      factorId,
    });

    if (challengeError) {
      setError(challengeError.message);
      setLoading(false);
      return;
    }

    const { error: verifyError } = await supabase.auth.mfa.verify({
      factorId,
      challengeId: challenge.id,
      code,
    });

    if (verifyError) {
      secureLogger.warn('MFA enrollment verify failed:', verifyError.message);
      setError('Invalid code. Please try again.');
      setCode('');
      setLoading(false);
    } else {
      secureLogger.debug('✅ MFA enrolled and verified — session upgraded to AAL2');
      onSuccess();
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-8">
        <div className="text-center mb-6">
          <div className="flex justify-center mb-4">
            <div className="p-3 bg-blue-100 rounded-full">
              <Shield className="h-8 w-8 text-blue-600" />
            </div>
          </div>
          <h2 className="text-2xl font-bold text-gray-900">Set Up Two-Factor Authentication</h2>
          <p className="text-gray-500 text-sm mt-2">
            Super admin accounts require 2FA. Scan the QR code with an authenticator app such as
            Google Authenticator or Authy, then enter the code to confirm.
          </p>
        </div>

        {initialising ? (
          <div className="flex justify-center py-6">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
          </div>
        ) : (
          <>
            {qrCode && (
              <div className="flex flex-col items-center mb-6">
                <div
                  className="p-3 bg-white border border-gray-200 rounded-lg"
                  /* qr_code is an SVG string generated by Supabase — safe to embed */
                  dangerouslySetInnerHTML={{ __html: qrCode }}
                />
                {secret && (
                  <div className="mt-3 text-center">
                    <p className="text-xs text-gray-500 mb-1">Or enter this setup key manually:</p>
                    <code className="text-xs font-mono bg-gray-100 px-2 py-1 rounded break-all select-all">
                      {secret}
                    </code>
                  </div>
                )}
              </div>
            )}

            <form onSubmit={handleVerify} className="space-y-4">
              {error && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-3 flex items-center space-x-2">
                  <AlertCircle className="h-5 w-5 text-red-500 flex-shrink-0" />
                  <p className="text-red-700 text-sm">{error}</p>
                </div>
              )}

              <div>
                <label
                  htmlFor="enroll-code"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Verification Code
                </label>
                <input
                  id="enroll-code"
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-center text-2xl tracking-[0.5em] font-mono"
                  placeholder="000000"
                  autoFocus
                  autoComplete="one-time-code"
                />
              </div>

              <button
                type="submit"
                disabled={loading || code.length !== 6 || !factorId}
                className="w-full text-white py-3 px-4 rounded-lg font-medium focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                style={{ backgroundColor: '#19ADF2' }}
              >
                {loading ? 'Enabling 2FA…' : 'Enable Two-Factor Authentication'}
              </button>
            </form>
          </>
        )}

        <button
          onClick={onCancel}
          className="w-full mt-4 text-gray-500 text-sm hover:text-gray-700 transition-colors"
        >
          Sign out and return to login
        </button>
      </div>
    </div>
  );
};
